### ISSUE TITLE
No distributions matching the version for future==0.13.dev

### ISSUE THREAD

**Issue by yohanboniface** [yohanboniface/redis-limpyd#87]
When doing a "pip install redis-limpyd" on a fresh virtualenv with python3.4:

```
No distributions matching the version for future==0.13.dev (from redis-limpyd)
```

I see that there is a `0.14.3` version out there, can we just upgrade?

**Comment by twidi** [comment]
@yohanboniface This is fixed, and merged, please upload a new package on pypi and update the documentation ;)
